name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "No build step needed"

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "" # 👈 disables GitHub status checks
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GROWWITH_SHOBY }}
          channelId: live
          projectId: growwith-shoby
